[Resolve]
# Mullvad Ad/Tracker/Malware Blocking DNS (IPv4)
DNS=194.242.2.9#all.dns.mullvad.net
# Mullvad Ad/Tracker/Malware Blocking DNS (IPv6)
DNS=2a07:e340::9#all.dns.mullvad.net

# SAFEHAVEN ENFORCEMENT
DNSOverTLS=yes
DNSSEC=yes
Cache=no
StaleRetentionSec=0
ReadEtcHosts=yes
MulticastDNS=false
LLMNR=no
FallbackDNS=
Domains=~.