[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.cloned-mac-address=random
ethernet.cloned-mac-address=random
ipv4.dhcp-send-hostname=0
ipv6.dhcp-send-hostname=0
connection.stable-id=${CONNECTION}/${BOOT}

# SAFEHAVEN ENFORCEMENT: Never trust public Wi-Fi DNS
ipv4.ignore-auto-dns=yes
ipv6.ignore-auto-dns=yes

[main]
hostname-mode=none
# SAFEHAVEN ENFORCEMENT: Strictly route to our zero-cache DoT Stub
dns=systemd-resolved